config/routes.rb
# frozen_string_literal: true

require_relative '../lib/route_scoper'
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :estimator_types, only: [:show, :create]
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'admin/contracts_approved' => 'admin/contracts#approved'
  get 'admin/contracts_archive' => 'admin/contracts#archive'
  post 'admin/assigns/:contract_id/assign_item/' => 'admin/assigns#assign_item'

  get 'admin/assigns/:contract_id' => 'admin/assigns#show'
  delete 'admin/assigns/:contract_id' => 'admin/assigns#destroy'
  put 'admin/assigns/:id' => 'admin/assigns#update_equipment'
  get 'admin/pending_team' => 'admin/contracts#pending_team'
  get 'admin/approved_team' => 'admin/contracts#approved_team'
  get 'admin/archive_team' => 'admin/contracts#archive_team'
  get 'admin/errors/error_404' => 'admin/errors#error_404'
  get 'admin/errors/no_perm' => 'admin/errors#no_perm'
  get 'admin/estimators_approved' => 'admin/estimators#estimators_approved'
  get 'admin/estimators_finished' => 'admin/estimators#estimators_finished'
  get 'admin/estimators_archive' => 'admin/estimators#estimators_archive'
  get 'admin/estimators/:id/status_change' => 'admin/estimators#status_change'
  get 'admin/estimator_types/:id/add_field' => 'admin/estimator_types#add_field'
  get 'admin/estimator_types/:id/edit_field/:id_field' => 'admin/estimator_types#edit_field', as: :edit_field
  get 'admin/estimator_types/:id/update_field/:id_field' => 'admin/estimator_types#update_field', as: :update_admin_field
  get 'admin/estimator_types/:id/destroy_field/:id_field' => 'admin/estimator_types#destroy_field'
  get 'admin/estimator_types/:id/export' => 'admin/estimator_types#export', as: :admin_export_estimator_type
  get 'admin/estimator_types_import' => 'admin/estimator_types#estimator_types_import', as: :admin_import_estimators_types
  post 'admin/estimator_types_import' => 'admin/estimator_types#estimator_types_import', as: :admin_import_estimators_types_post
  # get 'admin/tasks/invoices' => 'admin/tasks#invoices', as: :admin_invoices
  # get 'admin/tasks/download' => 'admin/tasks#download', as: :admin_invoices_download

  get 'admin/users/:id/edit_role' => 'admin/users#edit_role', as: :admin_user_edit_role
  patch 'admin/users/:id/update_role' => 'admin/users#update_role', as: :admin_user_update_role

  namespace :admin do
    resources :contracts do
      collection do
        get :popup_new
        post :popup_create
      end
      member do
        get :popup_edit
        patch :popup_update
      end
    end
    resources :roles

    resources :tasks, only: [] do
      collection do
        resources :invoices, only: [:index] do
          member do
            post :pay
            post :unpay
            get :history
            get :invoice_report
          end
          collection do
            get :archive
            get :download
          end
        end
      end
    end
  end

  resources :contracts, only: :create
  post "/sortable/reorder", to: "sortable#reorder"
  # scope RouteScoper.root do
  devise_for :users, controllers: {sessions: 'custom_sessions'}
  devise_scope :user do
    authenticated :user do
      root 'welcome#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  get 'accept_task' => 'welcome#accept_task'
  get 'accept_line' => 'welcome#accept_line'
  get 'email' => 'welcome#email'
  get 'cities' => 'welcome#cities'
  get 'attachments/:id' => 'welcome#attachments'
  get 'categories' => 'welcome#categories'
  get 'properties' => 'welcome#properties'
  get 'sign_in_for_api' => 'welcome#sign_in_for_api'
  get 'quick_books_integrations/callback' => 'quick_books_integrations#callback'
  get 'quick_books_integrations/' => 'quick_books_integrations#index'

  # root to: 'admin/users#index'
  # as :user do
  #   get 'users/profile', :to => 'devise/passwords#new', :as => :user_root
  # end

  namespace :admin do
    get '' => 'users#index'
    mount Sidekiq::Web => '/sidekiq'
    get 'tasks/moderation' => 'tasks#moderation'
    get 'tasks/:id/delete_document/:document' => 'tasks#delete_document'
    resources :users
    resources :tasks do
      put 'change_status' => 'tasks#change_status', as: :change_status
    end
    resources :equipment
    resources :vehicles, shallow: true do
      resources :maintenances, only: %i[index create update destroy]
    end
    resources :estimator_types
    resources :estimators
    resources :countries
    resources :task_payments
    resources :complaints
    resources :categories
    resources :contracts
    resources :work_zones
    resources :project_tasks
    resources :line_tasks
    resources :permissions
    resource :item_line_dv
    resources :settings, only: %i[index edit update settings_estimator], id: /[^\/]+/
    get 'new_change_status/:id' => 'contracts#new_change_status', as: :new_change_status
    resources :cash_out_payments do
      get 'transaction' => 'cash_out_payments#transaction'
    end
    get 'tracker' => 'users#tracker'
    get 'settings_estimator' => 'settings#settings_estimator'
    get 'settings_chs' => 'settings#settings_chs'
    get 'time_tracker' => 'users#time_tracker', as: :time_tracker
    get 'estimator_types/:id/display_views/:id_dv' => 'estimator_types#display_views', as: :estimator_types_display_views


    get 'get_user_data' => 'test#test'
  end

  namespace :api do
    post 'notifications/device' => 'feed_notifications#add_device'

    get 'users/hire_suggestions' => 'task_suggestions#hire_suggestions'
    get 'users/concierge_suggestions' => 'task_suggestions#concierge_suggestions'

    post 'users/up_balance' => 'users/up_balance'

    post 'users/me' => 'users#me_update'
    post 'users/reset_password' => 'users#reset_password'
    get 'users/me' => 'users#me'
    get 'users/token_active' => 'users#token_active'
    get 'users/:id' => 'users#show'
    get 'contractors' => 'users#contractors'
    devise_scope :user do
      post 'users/sign_in' => 'sessions#create'
    end
    # post 'users/sign_in' => 'users#sign_in'
    post 'users/sign_up' => 'users#sign_up'
    delete 'users/sign_out' => 'sessions#destroy'
    post 'users/update_description' => 'users#update_description'

    post 'tasks' => 'tasks#create'
    match 'location' => 'locations#create', via: %w[get post]
    delete 'tasks/:id' => 'tasks#destroy'
    post 'tasks/:id' => 'tasks#update'
    get 'tasks/cities' => 'tasks#cities'

    get 'tasks/concierge/active' => 'tasks#tasks_concierge_active'
    get 'tasks/concierge/archive' => 'tasks#tasks_concierge_archive'
    get 'tasks/concierge/pending' => 'tasks#tasks_concierge_pending'
    get 'tasks/concierge/available' => 'tasks#tasks_concierge_available'
    post 'tasks/:id/confirm/' => 'tasks#confirm_task'

    get 'tasks/my' => 'tasks#my_tasks'
    get 'tasks/hire' => 'tasks#tasks_hire'
    get 'tasks/hire/past' => 'tasks#tasks_hire_past'
    get 'tasks/hire/posted' => 'tasks#tasks_hire_posted'
    get 'tasks/hire/carrent' => 'tasks#tasks_hire_carrent'

    get 'tasks/:id' => 'tasks#show'

    get 'countries' => 'countries#index'
    get 'categories' => 'categories#index'
    get 'projects' => 'projects#index'
    get 'projects/:id' => 'projects#show'
    get 'contracts' => 'contracts#index'
    get 'contracts/:id' => 'contracts#show', as: :contract

    post 'tasks/:id/sugession' => 'task_suggestions#create'
    delete 'tasks/:id/sugession/:id' => 'task_suggestions#destroy'
    get 'tasks/:id/sugessions/' => 'task_suggestions#index'

    post 'tasks/:id/favorite_tasks' => 'favorite_tasks#create'
    delete 'tasks/:id/favorite_tasks' => 'favorite_tasks#destroy'

    get 'favorites_tasks' => 'favorite_tasks#index'

    get 'places' => 'places#index'
    get 'tasks/:id/place' => 'places#show'

    post 'tasks/:id/ratings' => 'ratings#create'

    post 'tasks/:id/statuses' => 'tasks#change_task_status'
    post 'users/:id/ratings' => 'ratings#show'

    post 'tasks/:id/message' => 'messages#create'
    get 'tasks/:id/messages/concierge' => 'messages#concierge_task_messages'
    get 'tasks/:id/messages/hire' => 'messages#hire_task_messages'

    get 'tasks/:id/messages/new_list' => 'messages#new_messages'

    get '/sugessions/:id/messages/' => 'messages#sugesstion_messages'
    get 'sugessions/:id' => 'task_suggestions#show'

    get 'payments/hire' => 'task_payments#hire_payments'
    get 'payments/concierge' => 'task_payments#concierge_payments'
    get 'payments/cashout_list' => 'task_payments#cashouts_lis'

    post 'payments/transfer' => 'task_payments#money_transfer'
    post 'payments/cashout' => 'task_payments#cashout'

    post 'tasks/:id/line_tasks' => 'line_tasks#create'
    post 'line_tasks/:id' => 'line_tasks#update'
    delete 'line_tasks/:id' => 'line_tasks#destroy'
    get 'line_tasks/:id' => 'line_tasks#show'

    resources :complaints
    resources :work_zones, only: :index
    resources :supervisors, only: :index
  end

  mount ActionCable.server => '/cable'
  # end


  ###

end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < Admin::CrudController
  before_action :set_entity, only: [:show, :edit, :update, :destroy, :generate_pdf_change_order, :change_status, :delete_document]
  # load_and_authorize_resource :only => [:show, :edit, :update, :destroy, :index]

  include SendZip

  def index
    @q = Task.distinct.search(params[:q])
    @entities = @q.result.page(params[:page]).per(params[:per_page])
  end

  def moderation
    @q = Task.search(status_eq: 'moderation')
    @entities = @q.result.page(params[:page]).per(params[:per_page])
    render 'admin/tasks/index'
  end

  def new
    @project_task = ProjectTask.find(params[:project])
    @entity = Kernel.const_get(@class_name).new
    @entity.build_place
    @categories = Category.active
    @users = Contract.where(status: :approved, team: [nil, false]).map { |e| e.user }
    if params[:line]
      @price = 0
      begin
        params[:line].count > 1
        @body = ''
        @price = 0
         params[:line].each do |l|
          @line = LineEstimator.find(l)
          @body += "QTY: #{@line.estimator.body_qty_clear(@line)}\n#{@line.name_scope}\n"
          @price += @line.trade_total.to_d
        end
      rescue
        @line = LineEstimator.find(params[:line])
        @body = "QTY: #{@line.estimator.body_qty_clear(@line)}\n#{@line.name_scope}"
        @price += @line.trade_total.to_d
      end
    end
  end

  def show
    @entity.build_place if @entity.place.nil?
    @line_task = LineTask.new
    respond_to do |format|
      format.html { render }
      format.zip { send_zip @entity.documents, filename: "attacments-#{@entity.title}.zip" }
    end
  end

  def edit
    @entity.build_place if @entity.place.nil?
    @line_task = LineTask.new
    @categories = Category.active
    @users = Contract.where(status: :approved, team: [nil, false]).map { |e| e.user }
  end

  def generate_pdf_change_order

  end

  def create
    @entity = Kernel.const_get(@class_name).new(entity_params)
    if @entity.save
      if params[:task][:line]
        params[:task][:line].split.each do |l|
        line = LineEstimator.find(l)
        line.update(task_id: @entity.id) if line
        end
      end
      address = (@entity.place.address if @entity.place)
      if @entity.concierge.present?
        UserMailer.new_task(@entity.concierge.email, @entity.title, @entity.description, address, @entity.id,
                            @entity.concierge.id, @entity.budget).deliver if @entity.concierge.present?
        Message.create(
            author_id: @entity.owner.id,
            recipient_id: @entity.concierge.id,
            message_body: "New Task",
            task_id: @entity.id,
            system: true
        )
      end

      if @entity.project_task
        if @entity.concierge.present?
          feed = FeedNotification.create(notification_type: 'new_task', task_id: @entity.id, task_title: @entity.title,
                                         message: @entity.description, task_owner_id: @entity.owner_id,
                                         suggestion_id: @entity.suggestion_id, user_id: @entity.concierge_id)
          #current_resource_owner.update_attribute(:balance, current_resource_owner.balance - (params[:task][:budget].to_i + (params[:task][:budget].to_i * 0.125)))

          if feed.save!
            NotificationsWorker.perform_async(feed.id)
            #task_payment = TaskPayment.new(user_id: @entity.owner_id, hire: true, task_id: @entity.id, budget: @entity.budget, persents: @entity.budget * 0.125)
            #task_payment.save
          end
        else
          feed = FeedNotification.create(notification_type: 'new_task', task_id: @entity.id, task_title: @entity.title, message: @entity.description, task_owner_id: @entity.owner_id)
          #current_resource_owner.update_attribute(:balance, current_resource_owner.balance - (params[:task][:budget].to_i + (params[:task][:budget].to_i * 0.125)))
          if feed.save!
            CreateTaskNotWorker.perform_async(feed.id)
            #task_payment = TaskPayment.new(user_id: @entity.owner_id, hire: true, task_id: @entity.id, budget: @entity.budget, persents: @entity.budget * 0.125)
            #task_payment.save

          end
        end
        redirect_to admin_task_path(@entity), notice: "Task was successfully created."
      else
        redirect_to admin_task_path(@entity), notice: "#{@class_name} was successfully created."
      end
    else
      render :new
    end
  end

  def delete_document
    file = @entity.documents.find(params[:document])
    file.purge
    redirect_to edit_admin_task_path(@entity)
  end

  def change_status
    status_service = Task::StatusChangeService.call(current_user,
                                                    task_id: @entity.id,
                                                    status: params[:status])
    message = if status_service.success?
                'Status was successfully updated'
              else
                "Status can't be changed"
              end
    redirect_to admin_task_path(@entity.id), notice: message
  end

  def update
    if @entity.update(entity_params)
      if params[:task][:line]
        line = LineEstimator.find(params[:task][:line])
        line.update(task_id: @entity.id) if line
      end
      if @entity.project_task
        redirect_to admin_task_path(@entity), notice: "Task was successfully updated."
      else
        redirect_to admin_task_path(@entity), notice: "#{@class_name} was successfully updated."
      end
    else
      @entity.build_place if @entity.place.nil?
      @line_task = LineTask.new
      @categories = Category.active
      @users = Contract.where(status: :approved, team: [nil, false]).map { |e| e.user }
      render :edit
    end
  end

  def destroy
    @entity.destroy
    if @entity.project_task
      redirect_to admin_project_task_path(@entity.project_task), notice: "Task was successfully updated."
    else
      redirect_to url_for(:action => :index), notice: "#{@class_name} was successfully deleted."
    end
  end

  private

  def set_class_name
    @class_name = 'Task'
  end

  def entity_params
    params.require(:task).permit(:title, :description, :city,
                                 :photo, :photo1, :photo2, :photo3, :photo4, :photo5, :photo6, :photo7,
                                 :delete_photo, :delete_photo1, :delete_photo2, :delete_photo3,
                                 :delete_photo4, :delete_photo5, :delete_photo6, :delete_photo7,
                                 :project_task_id, :concierge_id, :tender, :owner_id, :concierge_id, :date_limit,
                                 :budget, :status, :task_type, :phone, :project_task_id, :apartment, :date_start,
                                 :fact_start, :fact_end,
                                 place_attributes: [:id, :address, :task_id, :apartment],
                                 line_tasks_attributes: [:id, :task_id, :title, :budget, :status, :type_line, :status],
                                 documents: []).tap do |param|
      param[:task_type] = params[:task][:task_type].join(", ") unless params[:task][:task_type].nil?
      param[:date_limit] = parse_time(params[:task][:date_limit])
      param[:date_start] = parse_time(params[:task][:date_start])
      param[:fact_start] = parse_time(params[:task][:fact_start])
    end
  end

  def parse_time(param)
    Date.strptime(param, '%m/%d/%Y') rescue nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def photo_absent_class(photo)
    'photo-absent' unless photo.exists?
  end

  def photo_link(photo)
    photo.exists? ? photo.url : ''
  end

  def line_task_budget(line_task)
    line_task.budget_tax ? line_task.total_budget : '0.0'
  end

  def line_task_tax(line_task)
    line_task.budget ? line_task.budget_tax : '0.0'
  end

  def task_tax(task)
    task.total_sum ? task.budget_tax.round(2) : '0.0'
  end

  def task_profent_full(task)
    task.budget_tax ? task.profent_full.round(2) : '0.0'
  end

  def is_accepted?(task)
    task.confirmed? || task.done? || task.done_confirmed?
  end

  def task_status(task)
    if task.confirmed?
      'Accepted'
    else
      task.done_confirmed? ? 'Confirmed' : task.status&.capitalize
    end
  end
end

app/views/admin/tasks/show/_history.html.erb
<div class="tab-pane" id="history" role="tabpanel" aria-labelledby="workOrder-tab">
  <table class="project-table">
    <thead>
      <th>Time</th>
      <th>User</th>
      <th>Activity</th>
      <th>Changes</th>
    </thead>
    <tbody>
      <% @entity.versions.reverse.each do |version| %>
        <tr>
          <td><%= version.created_at.in_time_zone('MST').strftime('%d.%m.%Y %H:%M %Z') %></td>
          <td><%= User.find(version.whodunnit)&.full_name rescue nil %></td>
          <td><%= version.event %></td>
          <td>
            <% version.changeset.each do |key, value| %>
              <%= render 'admin/tasks/show/history_change', key: key, value: value %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/tasks/show/_pdf_documents.html.erb
<section class="tab-section">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" id="task-item" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="workOrder-tab" data-toggle="tab" href="#workOrder" role="tab" aria-controls="workOrder" aria-selected="true">Work
        order</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="changeOrders-tab" data-toggle="tab" href="#changeOrders" role="tab" aria-controls="changeOrders" aria-selected="false">Change
        orders</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="backChargers-tab" data-toggle="tab" href="#backChargers" role="tab" aria-controls="backChargers" aria-selected="false">Back
        chargers</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="invoices-tab" data-toggle="tab" href="#invoices" role="tab" aria-controls="invoices" aria-selected="false">Invoices</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" id="history-tab" data-toggle="tab" href="#history" role="tab" aria-controls="history" aria-selected="false">History</a>
    </li>
<% if @entity.lines.present? %>
    <li class="nav-item">
      <a class="nav-link" id="history-tab" data-toggle="tab" href="#quotes" role="tab" aria-controls="history" aria-selected="false">Line Quotes</a>
    </li>
<% end %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <%= render 'admin/tasks/show/history', entity: @entity %>
    <%= render 'admin/tasks/show/quotes', entity: @entity %>

    <!-- Tab 1 -->
    <div class="tab-pane active" id="workOrder" role="tabpanel" aria-labelledby="workOrder-tab">
      <table class="project-table">
        <thead>
        <tr>
          <th class="sort__title">Title <i class="sort__icon"></i></th>
          <th class="sort__title">Type<i class="sort__icon"></i></th>
          <th class="sort__title">Date (UTC)<i class="sort__icon"></i></th>
          <th class="fixed-width-140">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% if is_accepted?(@entity) %>
          <tr>
            <td><span class="td__project-title"><%= @entity.title %></span></td>
            <td>Work order</td>
            <td><%= file_date(@entity.work_order_pdf_path) %></td>
            <td>
              <a class="td__pdf" href="<%= @entity.work_order_pdf_path %>" target="_blank" title="Download purchase order"> 
                <i class="pdf-project__icon"></i>
              </a>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

    <!-- Tab 2 -->
    <div class="tab-pane" id="changeOrders" role="tabpanel" aria-labelledby="changeOrders-tab">
      <table class="project-table">
        <thead>
        <tr>
          <th class="sort__title">Title<i class="sort__icon"></i></th>
          <th class="sort__title">Type<i class="sort__icon"></i></th>
          <th class="sort__title">Status<i class="sort__icon"></i></th>
          <th class="sort__title">Change Budget (C$)<i class="sort__icon"></i></th>
          <th class="sort__title">GST OR HST TAX<i class="sort__icon"></i></th>
          <th class="sort__title">Sales Tax’s<i class="sort__icon"></i></th>
          <th class="sort__title">Date (UTC)<i class="sort__icon"></i></th>
          <th class="fixed-width-140">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% if is_accepted?(@entity) %>
          <% @entity.line_tasks.change_orders.each do |line| %>
            <tr>
              <td><span class="td__project-title edit-change-order__title"><%= line.title %></span></td>
              <td><%= line.type_line %></td>
              <td><%= line.status&.capitalize %></td>
              <td><%= sprintf('%.2f', line.budget) %></td>
              <td><%= line.task&.gst_calc %>%</td>
              <td>0%</td>
              <td><%= file_date(line.invoice_pdf_path) %></td>
              <td>
                <a class="td__pdf" href="<%= line.invoice_pdf_path %>" target="_blank" title="Download invoice">
                  <i class="pdf-project__icon"></i>
                </a>

                <a data-deleting_resource="delete_order_<%= line.id %>" data-toggle="modal" data-target="#confirm-delete" class="td__delete" rel="nofollow" title="Delete"><i class="delete-project__icon"></i></a>

                <a href="<%= admin_line_task_path(line) %>" data-method="delete" id="delete_order_<%= line.id %>" data-toggle="modal" data-target="#confirm-delete" class="td__delete" rel="nofollow" title="Delete"></a>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>

    <!-- Tab 3 -->
    <div class="tab-pane" id="backChargers" role="tabpanel" aria-labelledby="backChargers-tab">
      <table class="project-table">
        <thead>
        <tr>
          <th class="sort__title">Title <i class="sort__icon"></i></th>
          <th class="sort__title">Type<i class="sort__icon"></i></th>
          <th class="sort__title">Budget (C$)<i class="sort__icon"></i></th>
          <th class="fixed-width-140">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% if is_accepted?(@entity) %>
          <% @entity.line_tasks.back_charges.each do |line| %>
            <tr>
              <td><span class="td__project-title edit-back-charge__title"><%= line.title %></span></td>
              <td><%= line.type_line %></td>
              <td class="edit-back-charge__budget"><%= sprintf('%.2f', line.budget) %></td>
              <td>
                <a class="td__pdf" href="<%= line.invoice_pdf_path %>" target="_blank" title="Download invoice">
                  <i class="pdf-project__icon"></i>
                </a>

                <a data-deleting_resource="delete_order_<%= line.id %>" data-toggle="modal" data-target="#confirm-delete" class="td__delete" rel="nofollow" title="Delete"><i class="delete-project__icon"></i></a>

                <a href="<%= admin_line_task_path(line) %>" data-method="delete" id="delete_order_<%= line.id %>" data-toggle="modal" data-target="#confirm-delete" class="td__delete" rel="nofollow" title="Delete"></a>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>

    <!-- Tab 4 -->
    <div class="tab-pane" id="invoices" role="tabpanel" aria-labelledby="invoices-tab">
      <table class="project-table">
        <thead>
        <tr>
          <th class="sort__title">Title<i class="sort__icon"></i></th>
          <th class="sort__title">Type<i class="sort__icon"></i></th>
          <th class="sort__title">Budget (C$)<i class="sort__icon"></i></th>
          <th class="sort__title">GST OR HST TAX<i class="sort__icon"></i></th>
          <th class="sort__title">Sales Tax’s<i class="sort__icon"></i></th>
          <th class="sort__title">Date (UTC)<i class="sort__icon"></i></th>
          <th class="fixed-width-140">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% if @entity.done_confirmed? %>
          <tr>
            <td><span class="td__project-title"><%= @entity.title %></span></td>
            <td>Invoice</td>
            <td><%= @entity.budget_round %></td>
            <td><%= @entity.gst_calc %>%</td>
            <td>0%</td>
            <td><%= file_date(@entity.invoice_pdf_path) %></td>
            <td>
              <a class="td__pdf" href="<%= @entity.invoice_pdf_path %>" target="_blank" title="Download invoice">
                <i class="pdf-project__icon"></i>
              </a>
            </td>
          </tr>

          <% @entity.order_changes_confirmed.each do |line| %>
            <tr>
              <td><span class="td__project-title"><%= line.title %></span></td>
              <td>Change Invoice</td>
              <td><%= sprintf('%.2f', line.budget) %></td>
              <td><%= @entity.gst_calc %>%</td>
              <td>0%</td>
              <td><%= file_date(line.invoice_order_pdf_path) %></td>
              <td>
                <a class="td__pdf" href="<%= line.invoice_order_pdf_path %>" target="_blank" title="Download invoice">
                  <i class="pdf-project__icon"></i>
                </a>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

<style type="text/css">
  .history-change b {
    min-width: 150px;
    display: inline-block;
    font-weight: 600;
  }
</style>

app/views/admin/tasks/show/_quotes.html.erb
<div class="tab-pane" id="quotes" role="tabpanel" aria-labelledby="workOrder-tab">
  <table class="project-table">
  <thead>
  <tr>
    <th class="sort__title" width="15%">QTY <i class="sort__icon"></i></th>
    <th class="sort__title" width="36%">Description <i class="sort__icon"></i></th>
    <th class="sort__title" width="15%">Unit price <i class="sort__icon"></i></th>
    <th class="sort__title" width="15%">Line total <i class="sort__icon"></i></th>
    <th width="15%">
      <div class="">Actions</div>
    </th>
  </tr>
  </thead>
  <tbody>
  <% @entity.lines.each do |line| %>
    <tr>

      <td><strong><%= number_format(line.estimator.body_qty_clear(line)) %></strong></td>
      <td><%= line.name_scope %></td>
      <td><%= price_format(line.trade_price) %></td>
      <td><%= price_format(line.trade_total) %></td>
      <td><a href="<%= admin_estimator_path(line.estimator) %>"
             target="_blank" class="btn-outline-tr">Go to quote</a>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>