config/routes.rb
# frozen_string_literal: true

require_relative '../lib/route_scoper'
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :estimator_types, only: [:show, :create]
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'admin/contracts_approved' => 'admin/contracts#approved'
  get 'admin/contracts_archive' => 'admin/contracts#archive'
  post 'admin/assigns/:contract_id/assign_item/' => 'admin/assigns#assign_item'

  get 'admin/assigns/:contract_id' => 'admin/assigns#show'
  delete 'admin/assigns/:contract_id' => 'admin/assigns#destroy'
  put 'admin/assigns/:id' => 'admin/assigns#update_equipment'
  get 'admin/pending_team' => 'admin/contracts#pending_team'
  get 'admin/approved_team' => 'admin/contracts#approved_team'
  get 'admin/archive_team' => 'admin/contracts#archive_team'
  get 'admin/errors/error_404' => 'admin/errors#error_404'
  get 'admin/errors/no_perm' => 'admin/errors#no_perm'
  get 'admin/estimators_approved' => 'admin/estimators#estimators_approved'
  get 'admin/estimators_finished' => 'admin/estimators#estimators_finished'
  get 'admin/estimators_archive' => 'admin/estimators#estimators_archive'
  get 'admin/estimators/:id/status_change' => 'admin/estimators#status_change'
  get 'admin/estimator_types/:id/add_field' => 'admin/estimator_types#add_field'
  get 'admin/estimator_types/:id/edit_field/:id_field' => 'admin/estimator_types#edit_field', as: :edit_field
  get 'admin/estimator_types/:id/update_field/:id_field' => 'admin/estimator_types#update_field', as: :update_admin_field
  get 'admin/estimator_types/:id/destroy_field/:id_field' => 'admin/estimator_types#destroy_field'
  get 'admin/estimator_types/:id/export' => 'admin/estimator_types#export', as: :admin_export_estimator_type
  get 'admin/estimator_types_import' => 'admin/estimator_types#estimator_types_import', as: :admin_import_estimators_types
  post 'admin/estimator_types_import' => 'admin/estimator_types#estimator_types_import', as: :admin_import_estimators_types_post
  # get 'admin/tasks/invoices' => 'admin/tasks#invoices', as: :admin_invoices
  # get 'admin/tasks/download' => 'admin/tasks#download', as: :admin_invoices_download

  get 'admin/users/:id/edit_role' => 'admin/users#edit_role', as: :admin_user_edit_role
  patch 'admin/users/:id/update_role' => 'admin/users#update_role', as: :admin_user_update_role

  namespace :admin do
    resources :contracts do
      collection do
        get :popup_new
        post :popup_create
      end
      member do
        get :popup_edit
        patch :popup_update
      end
    end
    resources :roles

    resources :tasks, only: [] do
      collection do
        resources :invoices, only: [:index] do
          member do
            post :pay
            post :unpay
            get :history
            get :invoice_report
          end
          collection do
            get :archive
            get :download
          end
        end
      end
    end
  end

  resources :contracts, only: :create
  post "/sortable/reorder", to: "sortable#reorder"
  # scope RouteScoper.root do
  devise_for :users, controllers: {sessions: 'custom_sessions'}
  devise_scope :user do
    authenticated :user do
      root 'welcome#index'
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  get 'accept_task' => 'welcome#accept_task'
  get 'accept_line' => 'welcome#accept_line'
  get 'email' => 'welcome#email'
  get 'cities' => 'welcome#cities'
  get 'attachments/:id' => 'welcome#attachments'
  get 'categories' => 'welcome#categories'
  get 'properties' => 'welcome#properties'
  get 'sign_in_for_api' => 'welcome#sign_in_for_api'
  get 'quick_books_integrations/callback' => 'quick_books_integrations#callback'
  get 'quick_books_integrations/' => 'quick_books_integrations#index'

  # root to: 'admin/users#index'
  # as :user do
  #   get 'users/profile', :to => 'devise/passwords#new', :as => :user_root
  # end

  namespace :admin do
    get '' => 'users#index'
    mount Sidekiq::Web => '/sidekiq'
    get 'tasks/moderation' => 'tasks#moderation'
    get 'tasks/:id/delete_document/:document' => 'tasks#delete_document'
    resources :users
    resources :tasks do
      put 'change_status' => 'tasks#change_status', as: :change_status
    end
    resources :equipment
    resources :vehicles, shallow: true do
      resources :maintenances, only: %i[index create update destroy]
    end
    resources :estimator_types
    resources :estimators
    resources :countries
    resources :task_payments
    resources :complaints
    resources :categories
    resources :contracts
    resources :work_zones
    resources :project_tasks
    resources :line_tasks
    resources :permissions
    resource :item_line_dv
    resources :settings, only: %i[index edit update settings_estimator], id: /[^\/]+/
    get 'new_change_status/:id' => 'contracts#new_change_status', as: :new_change_status
    resources :cash_out_payments do
      get 'transaction' => 'cash_out_payments#transaction'
    end
    get 'tracker' => 'users#tracker'
    get 'settings_estimator' => 'settings#settings_estimator'
    get 'settings_chs' => 'settings#settings_chs'
    get 'time_tracker' => 'users#time_tracker', as: :time_tracker
    get 'estimator_types/:id/display_views/:id_dv' => 'estimator_types#display_views', as: :estimator_types_display_views


    get 'get_user_data' => 'test#test'
  end

  namespace :api do
    post 'notifications/device' => 'feed_notifications#add_device'

    get 'users/hire_suggestions' => 'task_suggestions#hire_suggestions'
    get 'users/concierge_suggestions' => 'task_suggestions#concierge_suggestions'

    post 'users/up_balance' => 'users/up_balance'

    post 'users/me' => 'users#me_update'
    post 'users/reset_password' => 'users#reset_password'
    get 'users/me' => 'users#me'
    get 'users/token_active' => 'users#token_active'
    get 'users/:id' => 'users#show'
    get 'contractors' => 'users#contractors'
    devise_scope :user do
      post 'users/sign_in' => 'sessions#create'
    end
    # post 'users/sign_in' => 'users#sign_in'
    post 'users/sign_up' => 'users#sign_up'
    delete 'users/sign_out' => 'sessions#destroy'
    post 'users/update_description' => 'users#update_description'

    post 'tasks' => 'tasks#create'
    match 'location' => 'locations#create', via: %w[get post]
    delete 'tasks/:id' => 'tasks#destroy'
    post 'tasks/:id' => 'tasks#update'
    get 'tasks/cities' => 'tasks#cities'

    get 'tasks/concierge/active' => 'tasks#tasks_concierge_active'
    get 'tasks/concierge/archive' => 'tasks#tasks_concierge_archive'
    get 'tasks/concierge/pending' => 'tasks#tasks_concierge_pending'
    get 'tasks/concierge/available' => 'tasks#tasks_concierge_available'
    post 'tasks/:id/confirm/' => 'tasks#confirm_task'

    get 'tasks/my' => 'tasks#my_tasks'
    get 'tasks/hire' => 'tasks#tasks_hire'
    get 'tasks/hire/past' => 'tasks#tasks_hire_past'
    get 'tasks/hire/posted' => 'tasks#tasks_hire_posted'
    get 'tasks/hire/carrent' => 'tasks#tasks_hire_carrent'

    get 'tasks/:id' => 'tasks#show'

    get 'countries' => 'countries#index'
    get 'categories' => 'categories#index'
    get 'projects' => 'projects#index'
    get 'projects/:id' => 'projects#show'
    get 'contracts' => 'contracts#index'
    get 'contracts/:id' => 'contracts#show', as: :contract

    post 'tasks/:id/sugession' => 'task_suggestions#create'
    delete 'tasks/:id/sugession/:id' => 'task_suggestions#destroy'
    get 'tasks/:id/sugessions/' => 'task_suggestions#index'

    post 'tasks/:id/favorite_tasks' => 'favorite_tasks#create'
    delete 'tasks/:id/favorite_tasks' => 'favorite_tasks#destroy'

    get 'favorites_tasks' => 'favorite_tasks#index'

    get 'places' => 'places#index'
    get 'tasks/:id/place' => 'places#show'

    post 'tasks/:id/ratings' => 'ratings#create'

    post 'tasks/:id/statuses' => 'tasks#change_task_status'
    post 'users/:id/ratings' => 'ratings#show'

    post 'tasks/:id/message' => 'messages#create'
    get 'tasks/:id/messages/concierge' => 'messages#concierge_task_messages'
    get 'tasks/:id/messages/hire' => 'messages#hire_task_messages'

    get 'tasks/:id/messages/new_list' => 'messages#new_messages'

    get '/sugessions/:id/messages/' => 'messages#sugesstion_messages'
    get 'sugessions/:id' => 'task_suggestions#show'

    get 'payments/hire' => 'task_payments#hire_payments'
    get 'payments/concierge' => 'task_payments#concierge_payments'
    get 'payments/cashout_list' => 'task_payments#cashouts_lis'

    post 'payments/transfer' => 'task_payments#money_transfer'
    post 'payments/cashout' => 'task_payments#cashout'

    post 'tasks/:id/line_tasks' => 'line_tasks#create'
    post 'line_tasks/:id' => 'line_tasks#update'
    delete 'line_tasks/:id' => 'line_tasks#destroy'
    get 'line_tasks/:id' => 'line_tasks#show'

    resources :complaints
    resources :work_zones, only: :index
    resources :supervisors, only: :index
  end

  mount ActionCable.server => '/cable'
  # end


  ###

end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_one_attached :main_image

  has_many :assigns, as: :assignable, dependent: :destroy
  has_many :contracts, through: :assigns



  scope :available, -> { where("available > ?", 0) }
  scope :added, -> { where("available = ?", 0) }


  belongs_to :category

  def testtest
    puts url_for(self.main_image)
  end

end

app/controllers/admin/equipment_controller.rb
class Admin::EquipmentController <  Admin::AdminController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]


  # GET /equipment
  # GET /equipment.json
  def index
    @equipments = Equipment.all
    @equipment = Equipment.new


    #modal window
    @contracts = Contract.approved
    #@init_contract = @contracts.first
    @init_contract = User.find(122).contract
    @init_contract_id = @init_contract.id
    @init_equipments = @init_contract.equipments

    

  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    respond_to do |format|
      format.html
      format.js {}
      format.json
    end
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to admin_equipment_index_url, notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to admin_equipment_index_url, notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to admin_equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:name, :category_id, :description, :total_owned, :available, :assigned, :damaged,
                                        :main_image)
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/admin/equipment/_form.html.erb
<%= form_for [:admin, @equipment], multipart: true do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@equipment.errors.count, "error")} prohibited this vehicle from being saved:" %>
      </h2>
      <ul>
        <% @equipment.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <ul class="file-list-fleet">
          <!-------img 1---------->
          <li class="file-list-fleet__item file-one-item">
            <div class="file-fleet__wrap">
              <label class="file-fleet-btn">
                <%= f.file_field :main_image, id: "fleet_photo1", class: "fleet-photo" %>

              </label>
              <figure class="fleet-thumbnail-wrap" id="fleet-thumbnail-wrap1" style="display:none;">
                <a data-fancybox="gallery" href="" id="fleet-gallery1">
                  <img class="fleet-thumbnail" id="fleet-thumbnail1" src="">
                </a>
              </figure>
              <label class="fleet-file-reset" id="fleet-reset1" for="fleet_delete_photo1" style="display:none;"><span class="reset__icon"></span></label>
              <input type="checkbox" value="1" name="" id="fleet_delete_photo1" class="delete_photo">
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="control-label">Name *</label>
        <%= f.text_field :name, class: "form-control check-field", required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="control-label">Description *</label>
        <%= f.text_field :description, class: "form-control check-field", required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <label class="control-label">Total Owned</label>

        <%= f.number_field :total_owned, class: "form-control", required: true %>

      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="control-label">Available</label>
        <%= f.number_field :available, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="control-label">Assigned</label>
        <%= f.number_field :assigned, class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group">
        <label class="control-label">Damaged</label>
        <%= f.number_field :damaged, class: "form-control", required: true %>
      </div>
    </div>
  </div>
  <div class="d-flex align-items-center form-btn-wrap">
    <div class="req-info mr-auto">* All fields are required</div>
    <button type="button" class="btn btn-noborder-cancel" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">CANCEL</span>
    </button>
    <%= f.submit "Save", class: "btn btn-noborder-ok item-save", disabled: false %>

  </div>
<% end %>

app/views/admin/equipment/_info.html.erb
      <div class="equipment-info__col-1">
        <div class="equipment-img">

          <figure class="equipment-img__big">
            <a data-fancybox="gallery" href="<%= url_for(@equipment.main_image) if @equipment.main_image.attached? %>">
              <img src="<%= url_for(@equipment.main_image) if @equipment.main_image.attached? %>">
            </a>
          </figure>
        </div>
      </div>
      <div class="equipment-info__col-2">
        <div class="row">
          <div class="col-md-6">
            <div class="slide-preview__item">
              <span class="slide-preview__item-title">Name</span>
              <p><%= @equipment.name %></p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="slide-preview__item">
              <span class="slide-preview__item-title">Description</span>
              <p><%= @equipment.description %></p>
            </div>
          </div>
        </div>
      </div>

app/views/admin/equipment/_inventory.html.erb
<table class="no-border-table">
  <thead>
  <tr>
    <th width="25%">Total Owned</th>
    <th width="25%">Assigned</th>
    <th width="25%">Available</th>
    <th width="25%">Damaged</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @equipment.total_owned %></td>
    <td><%= @equipment.available %></td>
    <td><%= @equipment.assigned %></td>
    <td><%= @equipment.damaged %></td>
  </tr>
  </tbody>
</table>
<hr>
<table class="no-border-table">
  <thead>
  <tr>
    <th width="40%">Astra Team Member</th>
    <th width="60%">Current Amount</th>
  </tr>
  </thead>
  <tbody>

  </tbody>
</table>

app/views/admin/equipment/edit.html.haml
%h1 Editing equipment

= render 'form'

= link_to 'Show', @equipment
\|
= link_to 'Back', equipment_index_path

app/views/admin/equipment/new.html.haml
%h1 New equipment

= render 'form'

= link_to 'Back', admin_equipment_index_url

app/views/admin/equipment/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @equipment.name
%p
  %b Category:
  = @equipment.category
%p
  %b Description:
  = @equipment.description
%p
  %b Total owned:
  = @equipment.total_owned
%p
  %b Available:
  = @equipment.available
%p
  %b Assigned:
  = @equipment.assigned
%p
  %b Damaged:
  = @equipment.damaged

= link_to 'Edit', edit_equipment_path(@equipment)
\|
= link_to 'Back', equipment_index_path

app/views/admin/equipment/show.js.erb
$('.info-section').html("<%= escape_javascript render('info', locals: @equipment ) %>");
$('.inventory-section').html("<%= escape_javascript render('inventory', locals: @equipment ) %>");